export const ADD_MEMBER = 'ADD_MEMBER';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const ADD_MEMBER_SETTING = 'ADD_MEMBER_SETTING';
export const SELECT_MEMBER = 'SELECT_MEMBER';

export const RECEIVE_MEMBER = 'RECEIVE_MEMBER';
export const GET_ALL_MEMBERS = 'GET_ALL_MEMBERS';
export const RECEIVE_ALL_MEMBERS = 'RECEIVE_ALL_MEMBERS';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const VisibilityFilters = {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE'
};

