export const ADD_TO_MEMBER = 'ADD_TO_MEMBER';
export const RECEIVE_TO_ADD_MEMBER = 'RECEIVE_TO_ADD_MEMBER';
export const GET_ALL_MEMBERS = 'GET_ALL_MEMBERS';
export const RECEIVE_MEMBERS = 'RECEIVE_MEMBERS';
